### ISSUE TITLE
Unable to find workflow after installing image

### ISSUE THREAD

**Issue by dktanwar** [bgruening/galaxy-rna-workbench#100]
I see that there are workflows present and are being installed by `Dockerfile`. But, after installing image using `Kitematic`, I can't find workflows.

![screen shot 2017-07-06 at 12 01 51](https://user-images.githubusercontent.com/8986859/27920583-13e2aaf8-6243-11e7-8256-f3f92fc8fa11.png)

**Comment by bgruening** [comment]
@dktanwar this is not the RNA-workbench which you started but the RNA-seq flavor. What is your command which you used to start it?

**Comment by dktanwar** [comment]
Oh no! Thank you @bgruening ! I am installing the right image now and will check for it. Sincere apologies for silly issue.

**Comment by bgruening** [comment]
No need to apologize ... Hope it works.

**Comment by dktanwar** [comment]
Worked!
