### ISSUE TITLE
conda error while testing a new galaxy tour

### ISSUE THREAD

**Issue by bagnacan** [bgruening/galaxy-rna-workbench#101]
dear all,

I used the tour builder to build the skeleton of a new tour for the rna-workbench, and I'm now enriching its content to launch FastQC over some training dataset. All steps work until I try to execute FastQC, whose run always fails with the error:
`Failed to activate conda environment! Error was: /export/galaxy-central/database/job_working_directory/000/285/tool_script.sh: line 13: /export/tool_deps/_conda/bin/activate: No such file or directory Fatal error: Exit code 1 ()`

Out of curiosity, I also tried to run the FastQC step within the already provided RNA-Seq tour, and it fails with the same error.

I'm testing the new tour using both chromium and firefox, and running the rna-workbench with the command:
`docker run -v "/my/local/path:/export" -d -p 8080:80 quay.io/bgruening/galaxy-rna-workbench`
 to copy my tour.yaml inside
`/my/local/path/galaxy-central/config/plugins/tours`

On the other hand, if I launch the rna-workbench container with:
`docker run -d -p 8080:80 quay.io/bgruening/galaxy-rna-workbench`
and then try the already provided RNA-Seq tour, the FastQC step succeedes.

What am I missing?

I will report the solution in the CONTRIBUTING.md

Thank you

**Comment by bgruening** [comment]
Can you look at `/export/tool_deps/_conda/bin/activate`? Is there something? Was the `/my/local/path` empty?

**Comment by bagnacan** [comment]
`ls /my/local/path` is not empty, and contains:
`ftp/  galaxy-central/  nginx_upload_store/  postgresql/  shed_tools/  tool_deps/  var/`
Conversely, I can't find `bin/activate` in the "_conda" directory within that path:
`ls /my/local/path/tool_deps/_conda/bin/activate` returns
`ls: cannot access '/my/local/path/tool_deps/_conda/bin/activate': No such file or directory`
the _conda directory contains:
`envs/  LICENSE.txt*  pkgs/  share/`

**Comment by bgruening** [comment]
Can you start in an empty folder and try again?

**Comment by bagnacan** [comment]
Thanks @bgruening. Restarting from an empty folder solved the issue. FastQC now runs from both my tour and the already provided RNA-Seq tour

**Comment by bgruening** [comment]
@bagnacan not sure what removed these files :(
Sorry, but glad that it works now.
