### ISSUE TITLE
feature request - STAR

### ISSUE THREAD

**Issue by colindaven** [bgruening/galaxy-rna-workbench#102]
Hi,

thanks for a great container.  It would be wonderful to have the STAR aligner in there since this is the most rapid and robust RNA-seq aligner in my estimation. I haven't had such good experiences with Hisat or Tophat, which has now been outdated for several years.

The tools are in the toolshed:
rgrnastar
star_fusion
and the STAR data manager

Might this be possible in the future or are there reasons to not support STAR in galaxy ?

Thanks,
Colin

**Comment by bgruening** [comment]
@colindaven I agree. Do you mind to create a PR against: https://github.com/bgruening/galaxy-rna-seq ... this will end up in this container at the end.

**Comment by colindaven** [comment]
Ok, cheers for the positive answer. I had a crack at it.

**Comment by bgruening** [comment]
Thanks @colindaven! If you like you can also add this tool to the tool table in the readme.

**Comment by colindaven** [comment]
Do you mean the Readme in this repo (and will STAR already be present here?) or do you mean the tool list in the deidcated galaxy-rna-seq repo below this ?

**Comment by colindaven** [comment]
Do you mean the Readme in this repo - I didn't add this yet (and will STAR already be present here?) or do you mean the tool list in the dedicated galaxy-rna-seq repo below this (I did add STAR there already) ?

**Comment by bgruening** [comment]
This repo here, yes. It might be also available now, but haven't checked it will be available in 17.09 for sure.
