### ISSUE TITLE
Panel sections

### ISSUE THREAD

**Issue by smithcr** [bgruening/galaxy-rna-workbench#11]
Currently, all tools in this workbench are under presented in Galaxy under the panel RNATools.
As our list of included tools grows longer, the usability of this drops.
I propose a new set of headers (dropping RNATools as it is already the rna-workbench)..e.g.:
- structure prediction
- mapping
- interaction prediction
  ...

**Comment by bgruening** [comment]
Good idea. All what we need to change is `--panel-section-name RNATools" `.

**Comment by bgruening** [comment]
I updated Cameron's old issue here, still valid. These sections could also be used as a table for the manuscript later or even in the one page thingy we need to hand in __this__ year.

**Comment by bgruening** [comment]
@dyusuf can you take over this one?

**Comment by dyusuf** [comment]
@bgruening yes I can help

**Comment by dyusuf** [comment]
@bgruening 

to confirm two points:

1. "RNATools" is already changed to "RNA Analysis"
2. to be modified: rna_workbench.yml -> tool_panel_section_label: "RNA Analysis"

**Comment by bgruening** [comment]
Also this can end up in a small table in the readme file, as a list of tools grouped into functionality ...

**Comment by dyusuf** [comment]
@bgruening  I have assigned the tools to the specific panels in rna_workbench.yml  and updated README.

**Comment by bgruening** [comment]
@dyusuf can we add links to the tools? I will close this one! I think this is nice! Thanks!

**Comment by dyusuf** [comment]
@bgruening yes, I will make the update with the links
