### ISSUE TITLE
403 Forbidden nginx/1.4.6 (Ubuntu)

### ISSUE THREAD

**Issue by bagnacan** [bgruening/galaxy-rna-workbench#113]
Dear all,

I'm trying to run the workbench by issuing:
`docker run -v "/path/to/my/docker/volume:/export" -d -p 8080:80 quay.io/bgruening/galaxy-rna-workbench`
I wait for the volume to be populated, then I point my browser to `localhost:8080`, but there I obtain "403 Forbidden nginx/1.4.6 (Ubuntu)"
I restarted the container by issuing:
`docker exec 5f0d49519f88 supervisorctl restart galaxy:`
which I always used to render the files that were updated inside the mounted volume. However, I obtain this as the output:
`galaxy:galaxy_nodejs_proxy: stopped`
`galaxy:handler0: ERROR (spawn error)`
`galaxy:handler1: ERROR (spawn error)`
`galaxy:galaxy_web: ERROR (spawn error)`
`galaxy:galaxy_nodejs_proxy: started`
And the problem persists.
What am I missing?

**Comment by bagnacan** [comment]
I just realised I used the same `-v "/path/to/my/docker/volume:/export"` volume path for two different containers, the second being the RNA workbench. I stopped the first container, but forgot to remove the content of the directory. I solved the problem restarting the RNA workbench **after** erasing the previous content

**Comment by bgruening** [comment]
Puh, I was clueless about this one :)
@bagnacan if you have time I need someone that debugs the workflow and the data library. For some reason we can not run the old scripts ... so I commented them out for the moment.
