### ISSUE TITLE
Add yourself as contributor 

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxy-rna-workbench#13]
Please feel free to add yourself as contributor: https://github.com/bgruening/galaxy-rna-workbench#contributers

ping @dyusuf @s-will @jfallmann @bebatut

**Comment by bgruening** [comment]
ping @dyusuf

**Comment by dyusuf** [comment]
https://travis-ci.org/bgruening/galaxy-rna-workbench/builds/186311068

error: no space left on device

**Comment by bgruening** [comment]
I know :( see discussion here: https://github.com/bgruening/galaxy-rna-workbench/pull/18

**Comment by bgruening** [comment]
@dyusuf travis is fixed! Thanks @jfallmann for contacting travis!
