### ISSUE TITLE
Galaxy tours are needed

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxy-rna-workbench#14]
* [x] Vienna-RNA
* [ ] mirDeep
* [x] RNA-seq

A few tours can be found here: https://github.com/galaxyproject/galaxy-tours

**Comment by bgruening** [comment]
@jfallmann started to work on it. Help probably welcome.

**Comment by jfallmann** [comment]
@bgruening I just started the docker instance and do not find RNAplfold in the tools list, is there something wrong on my side?

**Comment by jfallmann** [comment]
@bgruening  @s-will Ich hab mal eine mini tour durch ein paar VRNA tools gestartet, momentan fold, alifold und plot.
Eigentlich wuerd sichs ja anbieten in die Tour auch gleich Carna und co und noch mehr VRNA tools mitzunehmen, ich frag mich nur gerade ob es vielleicht mehr Sinn macht die Touren  eher tool-spezifisch zu machen. Die werden schon recht lang sonst kann ich mir vorstellen, Was sagt ihr?

**Comment by bgruening** [comment]
@jfallmann kleine tours sind immer gut, eine große kann auch nicht schaden, ich glaube sobald wir eine große haben können wir viele kleine spezifische anbieten, der code bleibt ja gleich gell?

**Comment by jfallmann** [comment]
Ja das stimmt am Code sollt sich nichts mehr aendern, kleine sind halt insofern einfacher als man nicht ueberlegen muss wie man die tools miteinander verknuepfen muss das es noch halbwegs Sinn macht.
Aber im Prinzip koennt ma natuerlich eine grosse fuer die ganze suite machen und daraus kleine fuer die einzelnen tools die vielleicht auch ein paar mehr optionen der tools einbauen

**Comment by s-will** [comment]
Hi @jfallmann, sehr cool! Entschuldige die vermutliche Blindheit, aber wo hast du denn die Tours? Mir fielen da schon sinnvolle Kombinationen (mit und ohne LocARNA)  ein:)

**Comment by jfallmann** [comment]
@s-will, liegt nicht an dir, die sind noch in meinem branch, ich mach einen PR auf sobald ich getestet hab ;)

**Comment by bgruening** [comment]
Super cool! Wie schwer findest du die Dinger @jfallmann?

**Comment by jfallmann** [comment]
@bgruening  Also die tour dich ich da hab ist relativ simpel, da kann man definitiv in jeder hinsicht noch nachlegen, also sowohl mehr options der benutzen tools einbauen als auch mehr tools ganz allgemein.
Vielleicht machts Sinn die tours auch nach topics zu gestalten, also sowas wie ncRNA prediction, interaction, usw. aber das braucht vor Allem Zeit, vielleicht Baustelle fuer Jannuar?

**Comment by bgruening** [comment]
Ja im Januar können wir noch viel machen, ich denke eine schöne Tool die wir auf der Startseite verlinken wäre notwendig, alles andere ist Bonus.

**Comment by jfallmann** [comment]
Weil ich dich grad hier hab, gibts einen einfachen Weg die tour yamls zu linten und zu testen? Meine galaxy instanz mag die tour noch immer nicht anzeigen, die drei core tours gehen aber nach docker neustart

**Comment by bgruening** [comment]
Bis auf sowas hier, noch nicht: http://www.yamllint.com/

**Comment by jfallmann** [comment]
Working on an RNA-Seq tour based on the training workflow, on the road, so internet is rare, will commit asap

**Comment by bgruening** [comment]
Both tours are awesome and are hopefully enough for the initial submission. A mirdeep tour would be cool for January/February.

**Comment by bgruening** [comment]
More is always better, but we have two nice ones, thanks to @jfallmann!
