### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxy-rna-workbench#15]
We need to have a new welcome page, highlighting the tools, the training and howto get started.

**Comment by bgruening** [comment]
Example page here: https://github.com/bgruening/docker-galaxy-stable/blob/16.10/galaxy/welcome.html

**Comment by bgruening** [comment]
This should probably added to the welcome page: http://bgruening.github.io/training-material//RNA-Seq/tutorials/ref_based

**Comment by bgruening** [comment]
How you add a customized welcome page to the container: https://github.com/bgruening/docker-galaxyp/blob/master/Dockerfile#L27

**Comment by bebatut** [comment]
I can do that. A simple welcome page? with the list of tools, links to the training and usage?

**Comment by bebatut** [comment]
From the README file or with a slightly different content?

**Comment by bgruening** [comment]
It should contains a structured but comprehensive overview of this container... With links to the tour, training... Further readings, more help and more information about Galaxy Docker, plus a nice image? RNA Whale and Galaxy?

**Comment by bebatut** [comment]
I do not have the admin right here. Can you activate the GitHub Pages via the repository's settings, pls? Thanks
A RNA whale??? :)

**Comment by bgruening** [comment]
@bebatut, Pages are activated.

**Comment by s-will** [comment]
Hi @bebatut, hi @bgruening,

concerning the "RNA whale", there are a few legal issues as well:
https://www.docker.com/brand-guidelines

So, in principle, we cannot modify the docker whale or even use it
without the word 'docker'...
At least, we can use the whale :)


In 12/22/2016 02:37 PM, Björn Grüning wrote:

**Comment by jfallmann** [comment]
Should we also add a mail address for people so they can reach us if tools are missing, not working or something like that? Maybe something like rna-workbench@denbi.rbc.de or whatever makes sense

**Comment by bgruening** [comment]
@jfallmann are github issues not enough?

**Comment by jfallmann** [comment]
@bgruening not sure, guess not all people who potentially use the docker image are using github, if that works it's fine for me, but I can imagine people would like to have some contact address for questions.
If we explain how to use the docker in the manuscript, and I guess we will, some people may never actually visit the github repo and will still want to have some way to communicate with us.

**Comment by bgruening** [comment]
We can create a google group if this is needed ...

**Comment by bgruening** [comment]
Can someone look at this: https://github.com/bgruening/galaxy-rna-workbench/pull/36
It probably needs a lot of love.

**Comment by jfallmann** [comment]
Let's wait for the reviews, maybe they suggest something anyway, but google group sounds good, for me personally github is enough

**Comment by bgruening** [comment]
Ok, sounds good! I have fixed one link on the welcome page and for me it looks ok. We could add a list of tools or a list of contributors and initial abstract etc to the frontpage, but for now I will close this issue. Please feel free to add additional information.
