### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxy-rna-workbench#16]
* [x] Linux
* [x] OSX
* [x] Windows

I would like to have Kitematik screenshots from OSX and/or Windows, howto start this workbench.

**Comment by bagnacan** [comment]
I'll try to produce some Kitematik screenshots on the 25th/26th on my OSX laptop

**Comment by bgruening** [comment]
Awesome, thanks!

**Comment by bagnacan** [comment]
I generated all the screenshots and provided a description for how the installation should be carried out in OSX. I included all images and text file in a .tar directory [here](https://www.dropbox.com/s/jfoofk1hnpcjmb1/screenshots.tar?dl=0). The wording should be fine, however I suggest you have a look at the sentences as I might have been too verbose/not as precise

**Comment by bgruening** [comment]
@bagnacan are you familiar with git and github already? If so feel free to create a PR with your md file and all pictures so we can include them.

**Comment by bagnacan** [comment]
@bgruening you're right, thank you. You'll receive a pull request later

**Comment by bgruening** [comment]
We have some initial documentation, thanks @bagnacan! I guess the markdown file can get a little bit of love, some spaces, maybe slightly smaller figures, but the content is great, thanks a lot!
