### ISSUE TITLE
cleanup readme

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxy-rna-workbench#17]
* [x] reference https://github.com/bgruening/docker-galaxy-stable as primary source of Docker documentation
* [x] what is included
* [x] de.NBI / ELIXIR logo

**Comment by jfallmann** [comment]
Several cases where docker-galaxy-stable is used instead of galaxy-rna-workbench, is this intended?

**Comment by bgruening** [comment]
Not intended, but maybe it's smarter to just link out to the documentation which is actual updated? Nevertheless, all occurrences on this page should be `galaxy-rna-workbench`.

**Comment by jfallmann** [comment]
Good point, but I would mention then somewhere that galaxy-rna-workbench is whats needed and not docker-galaxy-stable, people (me included) like to copy-paste

**Comment by bgruening** [comment]
Ok, I updated the readme file a little bit, please let me know if this is ok and reopen if not.
