### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by jfallmann** [bgruening/galaxy-rna-workbench#25]
Where should we store example data for tours and maybe workflows?
https://zenodo.org/ probably, but I think we should collect what we need so we have 
one DOI for all the data in the end to keep it consistent
Only problem is that adding data after DOI assignment seems to be impossible or at least a pain in the ass

**Comment by bgruening** [comment]
zenodo would be great, but any accessible URL should work
even this repo here if the data is small enough

**Comment by bgruening** [comment]
please add all data to this file: https://github.com/bgruening/galaxy-rna-workbench/blob/master/library_data.yaml

**Comment by bagnacan** [comment]
Hi all. @jfallmann I'm actually new to this, and not at all familiar with Zenodo or Figshare, but your question did rang a bell.. [Figshare's DOI versioning approach](https://support.figshare.com/support/solutions/articles/6000079064-can-i-edit-my-research-after-it-has-been-uploaded-) might be a solution to address the data add/edit DOI problem you mentioned.. Would it help?

**Comment by jfallmann** [comment]
Hi @bagnacan I'll check it out tomorrow and see if this could help, thanks for the idea

**Comment by bgruening** [comment]
I would prefer Zenodo, if not possible and the data is not too big we could simply have a dedicated github repo.

**Comment by bgruening** [comment]
I added a PS file in https://github.com/bgruening/galaxy-rna-workbench/pull/38

**Comment by bgruening** [comment]
Does anyone have a nice structure in dot-bracket format? This could be included as well.

**Comment by jfallmann** [comment]
I'll add data for the vrna tour to a git repo, shouldn't be too much. There's also a fasta with dot-bracket string and constraints if that's nice enough

**Comment by bgruening** [comment]
@jfallmann is all data now included? Can we close this?

**Comment by jfallmann** [comment]
@bgruenning can be closed
