### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by jfallmann** [bgruening/galaxy-rna-workbench#45]
Not sure if this really is a workbench related issue, however I just cleaned up my docker images  (docker rmi $(docker images -q)) and containers (docker rm $(docker ps -a -q)) and did a fresh docker pull of the galaxy-rna-workbench and it fails with the error below.
There is, however, plenty of space left, (/dev/sda3  96G   25G   67G  27% / )also plenty of inodes available (/dev/sda3 6406144   584052   5822092   10% /), any idea what the problem could be?

84c9ede9d5a6: Extracting [==================================================>] 1.578 GB/1.578 GB
e60bc2b3511a: Download complete 
143e2707dc73: Download complete 
287221e698f1: Download complete 
12f46cf7433f: Download complete 
a00f8c316b0c: Download complete 
816e728d44e5: Download complete 
989d8c6decfe: Download complete 
fb297202adef: Download complete 
b57dbf5c7c9c: Download complete 
1547b0055660: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /tool_deps/_cache/ac71fae5/lib/libLocARNA-1.6.so.1.0.0: no space left on device
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /tool_deps/_cache/ac71fae5/lib/libLocARNA-1.6.so.1.0.0: no space left on device.

**Comment by jfallmann** [comment]
Docker storage is /var/lib/docker, the directory looks fine as far as I can tell, I'll remove it and restart the demon

**Comment by jfallmann** [comment]
Same problem, however with df -i I saw that inode usage in /dev/dm-1 645480   271309    374171   43% /var/lib/docker/devicemapper/mnt/e08b494dcdca68c7f653943c2d9b9653e9c7f353fba50b5bd98b5f2aade2dbb5 ran out of inodes before the error occured. Don't know why this happens now and not before, but this seems to be a docker problem, as it runs out of inodes during extraction of the locarna layer.

**Comment by bgruening** [comment]
can you try the AUFS backend? Which Docker and Ubuntu version?

**Comment by jfallmann** [comment]
fedora23 and Docker version 1.10.3, build e03ddb8/1.10.3

**Comment by bgruening** [comment]
Habe sowas bei einer leeren Platte noch nicht gesehen, kannst ja mal Docker updaten, ich habe hier: Docker version 1.12.2, build bb80604

**Comment by jfallmann** [comment]
ich versuchs mal, meld mich wenn ich eine loesung gefunden hab

**Comment by bagnacan** [comment]
I'm experiencing this error now on a kitematic installation on MacOSX which previously worked. I tried the workbench on kitematic for windows today, and I was able to run it (I cannot re-try it on the windows machine as it's not mine, and I cannot access it)

**Comment by bgruening** [comment]
Can it be that your partition is just full. Can you simply test a Linux install?

**Comment by bagnacan** [comment]
Good idea, sorry it didn't come to my mind earlier. Btw I deleted the comment as the problem was somehow fixed by restarting kitematic twice: stopping, deleting the container and recreating it didn't solve the problem, so I tried the same but also deleting the vm. It didn't work, but when I re-restarted Kitematic, it went on flawlessly

**Comment by jfallmann** [comment]
@bgruening @bagnacan Is this the right thread for your issue?

**Comment by jfallmann** [comment]
Fixed the issue by updating docker, changing the storage-driver to overlay, disabling selinux in containers and moving the docker fs to another partition with more free inodes, so I'll close this issue

**Comment by bgruening** [comment]
Great, thanks for tracking this done!
