### ISSUE TITLE
Manuscript can be written

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxy-rna-workbench#53]
Hi all,

we have 3 weeks from now on to write this manuscript. Let coordinate a little bit and start writing :)

Thanks all!
Bjoern

**Comment by dyusuf** [comment]
Thanks, Bjoern! great news indeed. 

well, three-week is a bit stressing. any proposal on who is doing what?

**Comment by bgruening** [comment]
No plan yet, besides that we will work on the same Google Docs as the abstract.
We should describe example workflows and describe use-cases that RNAw will solve, in the same time make clear that it is a lego bricks system that can be used in a flexible way to create complete novel workflows + allows integration with other types of data analysis beyond RNA.

**Comment by jfallmann** [comment]
Awesome!

**Comment by bgruening** [comment]
Submitted. But we should include more useful workflows and testing is highly appreciated, we had a lot of additions since December and I upgrade the underlying Galaxy Image.
