### ISSUE TITLE
Would be good to add the Freiburg RNA-seq Galaxy Page

### ISSUE THREAD

**Issue by smithcr** [bgruening/galaxy-rna-workbench#8]
bgruening/training-material#159

**Comment by bgruening** [comment]
New training material is here and will be merged soon: https://github.com/bgruening/training-material/pull/159

**Comment by bgruening** [comment]
related PR: https://github.com/bgruening/galaxy-rna-workbench/pull/18
Discussion needed.

**Comment by bgruening** [comment]
Our training material could be added to the welcome page: http://bgruening.github.io/training-material//RNA-Seq/tutorials/ref_based

**Comment by bgruening** [comment]
We now have a very nice RNA-seq tour. It would be nice to mentione the training material somewhere on the frontpage or in the help menue, any idea? Than we can close this issue as well.

**Comment by bgruening** [comment]
@bebatut any idea where we can prominently advertise the training material in the Docker container?
Front-page? GTN logo?

**Comment by bgruening** [comment]
Added one RNA seq tutorial and close this now. Hope you are doing fine!
